CREATE DATABASE ShopDB; 
USE ShopDB; 

-- Create a table to store countries 
CREATE TABLE Countries (
    ID INT,
    Name VARCHAR(50),
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE GeoIPCache (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IPRange VARBINARY(16) NOT NULL,
    CountryID INT UNSIGNED NOT NULL
) ENGINE=MEMORY;

CREATE TABLE ProductDescription (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Description TEXT NOT NULL,
    ProductID INT UNSIGNED NOT NULL,
    CountryID INT UNSIGNED NOT NULL,
    INDEX idx_product_country (ProductID, CountryID)
) ENGINE=InnoDB;

CREATE TABLE Logs (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Message TEXT NOT NULL
) ENGINE=BLACKHOLE;

CREATE TABLE ProductReporting (
    Date DATE NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    Orders INT UNSIGNED NOT NULL
) ENGINE=MyISAM;